### ISSUE TITLE
Seeing student selected where we should no longer see it

### ISSUE THREAD

**Issue by ghachey** [OS4ED/openSIS-Responsive-Design#24]
![screen shot 2018-07-26 at 3 09 25 pm](https://user-images.githubusercontent.com/1091769/43241987-e7f24bd4-90e9-11e8-8ce5-b7d9b0109ade.png)

**Comment by openSISAdmin** [comment]
This is not a defect. This is a feature. A student record is held in the buffer so that the user can return to student's transnational record even after clicking at other areas of the application. In this screen shot example, the student is held in the buffer and is shown even when the user is in Courses. If you click on Student Schedule you will see the schedule for the student held in buffer. Therefore, the user does not have to search and locate the student again in order to view that student's schedule.

**Comment by ghachey** [comment]
In "some" places this may make sense as you suggest. However, many other places it is bad unintuitive UI and as a result confused all our users in the workshop. For example, there is no reason to keep a student "in a buffer" when user navigates to something unrelated such as in the school setup. I've never seen such behavior in good User Interface design.
