### ISSUE TITLE
Upgrade from 7.0 to 7.1 Fails

### ISSUE THREAD

**Issue by cls-registrar** [OS4ED/openSIS-Responsive-Design#50]
![2019-01-18](https://user-images.githubusercontent.com/42213555/51421565-c0b54080-1b6d-11e9-95f9-c30f5ae70e27.png)

**Comment by fcortesjp** [comment]
Not sure if this is the same or related issue but when I upgraded from 6.5 to 7.1 (as per the file downloaded), the upgraded completed succesfully but on the installation shows version 7.0 instead of 7.1
![image](https://user-images.githubusercontent.com/10264915/53463804-ff180800-3a15-11e9-8f61-3e08e2398bf0.png)

**Comment by fcortesjp** [comment]
> Not sure if this is the same or related issue but when I upgraded from 6.5 to 7.1 (as per the file downloaded), the upgraded completed succesfully but on the installation shows version 7.0 instead of 7.1
> ![image](https://user-images.githubusercontent.com/10264915/53463804-ff180800-3a15-11e9-8f61-3e08e2398bf0.png)

Opensis confirmed that the version number was not updated in sql but this issue would be fixed.

**Comment by openSISAdmin** [comment]
This error is specific to your case, not a generic system issue.
